# Generated by Django 3.2.6 on 2021-08-26 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='fullname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleeka.client'),
        ),
        migrations.AlterField(
            model_name='withdrwal',
            name='fullname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleeka.client'),
        ),
    ]
