# Generated by Django 3.2.6 on 2021-08-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0004_rename_amount_to_deposit_withdrwal_amount_to_withdrawl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('amount_to_deposit', models.IntegerField(null=True)),
                ('balance', models.IntegerField(null=True)),
            ],
        ),
    ]
