# Generated by Django 3.2.6 on 2021-08-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0006_alter_depo_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depo',
            name='fullname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
