# Generated by Django 3.1.7 on 2021-08-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0009_auto_20210827_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='fullname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleeka.client'),
        ),
    ]
