# Generated by Django 3.1.7 on 2021-08-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0010_auto_20210827_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='withdrwal',
            name='balance',
        ),
    ]
