# Generated by Django 3.2.6 on 2021-08-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0012_auto_20210827_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transa',
            new_name='Transaction',
        ),
        migrations.RemoveField(
            model_name='withdrwal',
            name='fullname',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='fullname',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount_to_withdrawl',
        ),
        migrations.AddField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='groupNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending-verification', 'Pending-verification')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teleeka.group'),
        ),
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.CharField(choices=[('Jinja-Youth', 'Jinja-Youth'), ('Kampala-Youth', 'Kampala-Youth'), ('Entebbe-Youth', 'Entebbe-Youth'), ('Mbale-Youth', 'Mable-Youth'), ('Gulu-Youth', 'Gulu-Youth'), ('Arua-Youth', 'Arua-Youth')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Withdrwal',
        ),
    ]
