# Generated by Django 3.1.7 on 2021-08-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0014_auto_20210828_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='client',
            new_name='clientName',
        ),
    ]
