# Generated by Django 3.1.7 on 2021-08-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0015_auto_20210828_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
