# Generated by Django 3.1.7 on 2021-08-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0017_auto_20210828_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='note',
        ),
    ]
