# Generated by Django 3.2.7 on 2021-09-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0021_auto_20210901_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='group',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='group',
        ),
        migrations.RemoveField(
            model_name='withdrawl',
            name='group',
        ),
        migrations.DeleteModel(
            name='SavingGroup',
        ),
    ]
