# Generated by Django 3.2.7 on 2021-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0022_auto_20210903_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
