# Generated by Django 3.2.7 on 2021-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleeka', '0023_auto_20210903_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reason',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], max_length=200, null=True),
        ),
    ]
